version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  # --- Infrastructure ---
  infra:up:
    desc: Start Traefik (for domain testing)
    cmds:
      - docker compose up -d traefik

  infra:postgres:
    desc: Start PostgreSQL (for DB_DRIVER=pgx)
    cmds:
      - docker compose --profile postgres up -d postgres

  infra:down:
    desc: Stop all infrastructure
    cmds:
      - docker compose --profile postgres down

  infra:reset:
    desc: Reset infrastructure (delete volumes and restart)
    cmds:
      - docker compose --profile postgres down -v

  # --- Install ---
  install:tui:
    desc: Install TUI as 'deeploy' binary
    cmds:
      - go build -o $(go env GOPATH)/bin/deeploy ./cmd/tui

  # --- Dev ---
  dev:tui:
    desc: TUI client
    cmds:
      - DEBUG=1 go run ./cmd/tui

  dev:tui:debug:
    desc: Debug TUI (start, then attach in Neovim with <leader>dc, stop with task dev:tui:debug:stop)
    cmds:
      - tmux new-window -n debug 'dlv debug ./cmd/tui --headless --listen=:43000'

  dev:tui:debug:stop:
    desc: Stop TUI debug session
    cmds:
      - tmux kill-window -t debug

  dev:server:
    desc: Start dev server (SQLite as default)
    cmds:
      - task --parallel tailwind templ:server

  dev:server:postgres:
    desc: Start dev server (PostgreSQL - configure .env)
    cmds:
      - task --parallel tailwind templ:server infra:postgres

  dev:docs:
    desc: Docs website
    cmds:
      - task --parallel tailwind templ:docs

  tailwind:
    cmds:
      - "{{.TAILWIND_CMD}} -i ./internal/shared/assets/css/input.css -o ./internal/shared/assets/css/output.css --watch"

  templ:server:
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/server" --open-browser=false

  templ:docs:
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/docs" --open-browser=false

  dev:all:
    desc: Run server + docs (ports 8090 + 8091)
    cmds:
      - task --parallel dev:server dev:docs
