version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  # --- Infrastructure ---
  infra:up:
    desc: Start Postgres and Traefik
    cmds:
      - docker compose up -d postgres traefik

  infra:down:
    desc: Stop all infrastructure
    cmds:
      - docker compose down

  infra:reset:
    desc: Reset infrastructure (delete volumes and restart)
    cmds:
      - docker compose down -v
      - docker compose up -d postgres traefik

  # --- Dev ---
  dev:tui:
    desc: TUI client
    cmds:
      - DEBUG=1 go run ./cmd/tui

  dev:server:
    desc: VPS server (starts Postgres and Traefik)
    deps: [infra:up]
    cmds:
      - task --parallel tailwind templ:server

  dev:docs:
    desc: Docs website
    cmds:
      - task --parallel tailwind templ:docs

  tailwind:
    cmds:
      - "{{.TAILWIND_CMD}} -i ./internal/shared/assets/css/input.css -o ./internal/shared/assets/css/output.css --watch"

  templ:server:
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/server" --open-browser=false

  templ:docs:
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/docs" --open-browser=false

  dev:all:
    desc: Run server + docs (ports 8090 + 8091)
    cmds:
      - task --parallel dev:server dev:docs
