package config

import (
	"fmt"
	"os"

	"github.com/joho/godotenv"
)

type Config struct {
	AppEnv           string
	Port             string
	DBDriver         string // "sqlite" or "pgx"
	DBConnection     string // connection string
	JWTSecret        string
	EncryptionKey    string
	CookieSecure     bool
	BuildDir         string
	TraefikConfigDir string // Directory for Traefik dynamic config files
}

func Load() *Config {
	godotenv.Load()

	appEnv := getEnv("APP_ENV", "development")

	// Database config - SQLite default, PostgreSQL optional
	dbDriver := getEnv("DB_DRIVER", "sqlite")
	dbConnection := getEnv("DB_CONNECTION", "./data/deeploy.db?_pragma=foreign_keys(1)&_pragma=journal_mode(WAL)")

	// Always require secrets (generated by install script)
	jwtSecret := requireEnv("JWT_SECRET", "min 32 characters")
	encryptionKey := requireEnv("ENCRYPTION_KEY", "exactly 32 characters")

	return &Config{
		AppEnv:           appEnv,
		Port:             getEnv("PORT", "8090"),
		DBDriver:         dbDriver,
		DBConnection:     dbConnection,
		JWTSecret:        jwtSecret,
		EncryptionKey:    encryptionKey,
		CookieSecure:     false, // HTTP allowed, Traefik enforces HTTPS when domain configured
		BuildDir:         getEnv("BUILD_DIR", "/tmp/deeploy-builds"),
		TraefikConfigDir: getEnv("TRAEFIK_CONFIG_DIR", "/traefik/dynamic"),
	}
}

func (c *Config) IsDevelopment() bool {
	return c.AppEnv == "development"
}

func (c *Config) IsProduction() bool {
	return c.AppEnv == "production"
}

func getEnv(key, fallback string) string {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	return value
}

func requireEnv(key, hint string) string {
	value := os.Getenv(key)
	if value == "" {
		fmt.Printf("\n Missing required environment variable: %s\n", key)
		fmt.Printf("   Expected: %s\n\n", hint)
		os.Exit(1)
	}
	return value
}
