package config

import (
	"fmt"
	"os"

	"github.com/joho/godotenv"
)

type Config struct {
	AppEnv        string
	Port          string
	DatabaseURL   string
	JWTSecret     string
	EncryptionKey string
	CookieSecure  bool
	BuildDir      string
}

func Load() *Config {
	godotenv.Load()

	appEnv := getEnv("APP_ENV", "development")

	// Always require secrets (generated by install script)
	databaseURL := requireEnv("DATABASE_URL", "postgres://user:pass@host:5432/deeploy")
	jwtSecret := requireEnv("JWT_SECRET", "min 32 characters")
	encryptionKey := requireEnv("ENCRYPTION_KEY", "exactly 32 characters")

	return &Config{
		AppEnv:        appEnv,
		Port:          getEnv("PORT", "8090"),
		DatabaseURL:   databaseURL,
		JWTSecret:     jwtSecret,
		EncryptionKey: encryptionKey,
		CookieSecure:  false, // HTTP allowed, Traefik enforces HTTPS when domain configured
		BuildDir:      getEnv("BUILD_DIR", "/tmp/deeploy-builds"),
	}
}

func (c *Config) IsDevelopment() bool {
	return c.AppEnv == "development"
}

func (c *Config) IsProduction() bool {
	return c.AppEnv == "production"
}

func getEnv(key, fallback string) string {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	return value
}

func requireEnv(key, hint string) string {
	value := os.Getenv(key)
	if value == "" {
		fmt.Printf("\n Missing required environment variable: %s\n", key)
		fmt.Printf("   Expected: %s\n\n", hint)
		os.Exit(1)
	}
	return value
}
